//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleEchoBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id { get; set; }
        public string name { get; set; }
        public string gender { get; set; }
        public Nullable<decimal> age { get; set; }
        public string budget { get; set; }
        public Nullable<bool> married { get; set; }
        public Nullable<bool> kids { get; set; }
        public string mobile { get; set; }
        public Nullable<decimal> smile { get; set; }
        public Nullable<decimal> anger { get; set; }
        public Nullable<decimal> happiness { get; set; }
        public Nullable<bool> eyeMakeup { get; set; }
        public Nullable<bool> lipMakeup { get; set; }
        public string glasses { get; set; }
        public string hair { get; set; }
        public Nullable<decimal> bald { get; set; }
        public string hairColor { get; set; }
        public Nullable<decimal> moustache { get; set; }
        public Nullable<decimal> beard { get; set; }
        public string emotion { get; set; }
        public string makeupStr { get; set; }
        public string smileStr { get; set; }
        public string angerStr { get; set; }
        public string sellInCar { get; set; }
        public Nullable<decimal> sellInOriginPrice { get; set; }
        public Nullable<decimal> sellInPrice { get; set; }
        public Nullable<int> sellInYear { get; set; }
        public string likedCar { get; set; }
        public string photoUrl { get; set; }
    }
}
